ActionCable
dastanabeuov/qna pull request #18
Opened 2021-01-11 06:49 UTC by dastanabeuov

2021-01-11 19:33 UTC, IvanShamatov requested changes

2021-01-11 19:33 UTC, IvanShamatov commented on app/controllers/comments_controller.rb
> +    if Answer.all.include?(@commentable)
очень плохое решение. Всякий раз, когда делается ModelName.all мы вытаскиваем ВСЕ из базы. 
судя по тому что это коммент, то на любое добавление коммента мы будем вытаскивать в оперативку все ответы, коих по идее на порядок меньше чем комментов, но гораздо больше вопросов. Тут чудовищная нагрузка будет

2021-01-11 19:33 UTC, IvanShamatov commented on app/controllers/comments_controller.rb
> +    end
хм, странно, а почему нет никакого броадкаста коммента, похоже эта часть задания не сделана

2021-01-11 19:33 UTC, IvanShamatov commented on app/views/comments/_comments.html.erb
> +<ul class="#{resource_name(resource)}-#{resource.id}-comments-list">
было бы неплохо единообразие шаблонов сохранить, если уж slim, то везде

2021-01-11 19:33 UTC, IvanShamatov commented on spec/features/question/qcable_spec.rb
> +    scenario "question appears on another user's page" do
добавление ответов тоже очень важно, особенно важно проверить их функциональность после добавления., что мол никакие лишние ссылки не показываются не тем юзерам

2021-01-11 19:33 UTC, IvanShamatov commented on spec/controllers/comments_controller_spec.rb
> +
жаль

2021-01-13 16:13 UTC, dastanabeuov commented on app/controllers/comments_controller.rb
> +    if Answer.all.include?(@commentable)
Исправил изменил на @commentable.class.name == 'Answer'

2021-01-13 16:40 UTC, dastanabeuov commented on app/controllers/comments_controller.rb
> +    end
Ойбай совсем забыл про реализацию комментов...)

2021-01-14 10:07 UTC, dastanabeuov commented on app/views/comments/_comments.html.erb
> +<ul class="#{resource_name(resource)}-#{resource.id}-comments-list">
Изменил...но что то сортировка перестал работать....хм

2021-01-17 14:41 UTC, dastanabeuov commented on spec/controllers/comments_controller_spec.rb
> +
Дополнил...

2021-01-17 14:49 UTC, dastanabeuov commented on spec/features/question/qcable_spec.rb
> +    scenario "question appears on another user's page" do
Дополнил тест для добавления ответов

2021-01-18 07:55 UTC, IvanShamatov commented on app/controllers/comments_controller.rb
> +    if Answer.all.include?(@commentable)
класс можно проверить с помощью метода is_a?()
`if @commentable.is_a?(Answer)`

2021-01-18 08:09 UTC, IvanShamatov requested changes
гон подключил правильно, использования hbs не нашел.

2021-01-18 08:09 UTC, IvanShamatov commented on app/views/comments/_comments.html.erb
> +<p>Comments</p>
почему этот паршл в erb?

2021-01-18 08:09 UTC, IvanShamatov commented on spec/controllers/comments_controller_spec.rb
> +  	context 'with question comment' do
тут не хватает линтера, ты рубокопом файлы свои проходил? обязательно добавь рубокоп

2021-01-18 08:09 UTC, IvanShamatov commented on app/assets/javascripts/templates/answer.hbs.example
> +<div id="answer-id-{{answer.id}}">
файл-то норм, но он же нигде не используется

2021-01-19 03:00 UTC, dastanabeuov commented on app/controllers/comments_controller.rb
> +    if Answer.all.include?(@commentable)
Отличный метод Иван, спасибушки!

2021-01-19 03:04 UTC, dastanabeuov commented on app/views/comments/_comments.html.erb
> +<p>Comments</p>
Я его пытался преобразовать в slim, вот только после именения перестает сортировать...я не понял почему так происходит( и потому оставил как есть в .erb

2021-01-19 03:22 UTC, dastanabeuov commented on spec/controllers/comments_controller_spec.rb
> +  	context 'with question comment' do
Робокопа нет. А что за линтер? Робокоп сам найдет, и подскажет кажется если не ошибаюсь...хм

2021-01-19 03:25 UTC, dastanabeuov commented on app/assets/javascripts/templates/answer.hbs.example
> +<div id="answer-id-{{answer.id}}">
Следом отправлю коммит с использованием

2021-01-19 04:23 UTC, dastanabeuov commented on spec/controllers/comments_controller_spec.rb
> +  	context 'with question comment' do
А Робокопом проверять всю директорию Rails?
Или только отдельную часть?

2021-01-27 06:25 UTC, IvanShamatov approved these changes

2021-01-30 16:13 UTC, merged